### ISSUE TITLE
tedna crashes at the 'Merging repeats' step

### ISSUE THREAD

**Issue by jorisbertrand** [mzytnicki/tedna#1]
Good morning,
after a while, tedna crashes with the following error message: 
Merging repeats (3095 elements)...
/tmp/.lsbtmp24018/.lsbatch/1554883222.499949: line 8: 39590 Segmentation fault      (core dumped) ./tedna -1 (...) -2 (...) -k 61 -i 350 -t 50 -o (...) --max-reads 10000000 -m 200 -M 6000
Could you help me to try to figure out what happens? 
Cheers

**Comment by mzytnicki** [comment]
@jorisbertrand Hard to say.  `Segmentation fault` is not very informative.  Would you mind sharing your data?  I could see what is going wrong.

**Comment by jorisbertrand** [comment]
It looks that it is a memory problem. It works when I decrease the number of reads to --max-reads 500000 for instance.

**Comment by mzytnicki** [comment]
That may be true, but I would expect a `std::bad_alloc` exception instead.
Something must be wrong here.
